//! The test harness this frontend generates when it lowers for a test run.
//!
//! A `#[test]` method is an ordinary Java method with no caller. Something has to reach it from a
//! `main`, and that something is generated here as **more Java source** — not as bytecode, and not
//! through reflection. Both choices are forced: the lowered tree is what a backend compiles, so a
//! harness that is Java source works under `javac` and the in-process compiler alike, and
//! `jals-hir`'s embedded stubs carry no `java.lang.reflect`, so a reflective harness would compile
//! on one backend and not the other.
//!
//! Two generated shapes, and the split between them is *reachability*:
//!
//! - One **shim per test class**, in that class's own package, so a package-private test method is
//!   callable with a plain static call. Per class rather than per package because the dispatch is
//!   a chain of `String.equals` branches and a method's bytecode is capped at 64 KiB — a project
//!   whose tests live in one package would eventually stop compiling.
//! - One **root harness** in the default package, holding `main`. It answers `--list` and routes
//!   an id to its shim. The default package can name every other package but no package can name
//!   it, which is the right direction for something only a launcher invokes.
//!
//! A test passes when the harness prints [`OK_SENTINEL`] for it. Exit status alone would also be
//! `1` for "could not find or load main class", and `0` for a test body that called
//! `System.exit(0)` — neither is the test's own verdict.
//!
//! **Changing what this module emits means bumping `DialectFrontend`'s `caps().version`.** A
//! lowering is restored from the artifact cache without the frontend running at all, so an
//! unchanged version keeps serving the harness generated by the previous one — which fails as a
//! codegen bug in a project that has simply not been rebuilt.

use alloc::format;
use alloc::string::String;
use alloc::vec::Vec;
use core::fmt::Write as _;

use jals_storage::RelativePath;
use jals_syntax::ast::{AstNode, SourceFile};
use jals_syntax::cfg::TestHost;
use jals_syntax::{Parse, SyntaxKind, SyntaxNode};

/// The logical directory the generated sources live under.
///
/// Outside every source root on purpose: the tree a backend compiles is addressed by logical path,
/// and `LoweredTree` rejects a duplicate, so generated output needs a place an authored file
/// cannot also claim.
const GENERATED_ROOT: &str = "jals-test";

/// The class holding `main`, in the default package.
///
/// Public because it is the third half of the contract with the runner: the launcher has to name
/// a main class, and inventing the name on that side would be a second place for it to live.
pub const HARNESS_CLASS: &str = "JalsTestHarness";

/// The prefix of a per-class shim. `$` is an ordinary identifier character in Java (JLS §3.8) and
/// is what keeps the name clear of anything a person would write.
const SHIM_PREFIX: &str = "JalsTest$";

/// What the harness prints on the standard output when a test returned normally.
///
/// The runner treats a test as passed only on seeing this, so a body that exits the JVM with a
/// success status is still reported as the failure it is.
pub const OK_SENTINEL: &str = "jals-test:ok";

/// The argument that makes the harness enumerate instead of run.
pub const LIST_ARGUMENT: &str = "--list";

/// The argument that suppresses [`OK_SENTINEL`].
///
/// Passed when the runner is not capturing: the tests are writing to the terminal the reader is
/// watching, and the sentinel is machinery, not something a test said. With capture off the
/// runner has no output to read anyway, so the exit status is the verdict and the line has no
/// remaining job.
pub const QUIET_ARGUMENT: &str = "--quiet";

/// One `#[test]` method, named the way the outside world addresses it.
///
/// The package is a field rather than a prefix of `class`, because a nested test class makes the
/// two indistinguishable from the outside: `com.example.Outer.Inner` splits after `example`, and
/// nothing in the name says where.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) struct DiscoveredTest {
    /// The declaring package, empty for the default package.
    package: String,
    /// The nested type chain that declares the method, dotted as source writes it: `MathTest`, or
    /// `Outer.Inner`.
    class: String,
    /// The method's own name.
    method: String,
    ignore: bool,
    should_fail: bool,
}

impl DiscoveredTest {
    /// The id the runner and the harness agree on: `com.example.MathTest#adds`.
    fn id(&self) -> String {
        format!("{}#{}", self.qualified_class(), self.method)
    }

    /// The declaring class, package included.
    fn qualified_class(&self) -> String {
        if self.package.is_empty() {
            self.class.clone()
        } else {
            format!("{}.{}", self.package, self.class)
        }
    }

    /// The generated shim's simple name for this test's class. A nested chain keeps every level,
    /// with `$` for the dots, so two `Inner`s under different outers stay distinct.
    fn shim_name(&self) -> String {
        format!("{SHIM_PREFIX}{}", self.class.replace('.', "$"))
    }

    /// How the root harness, which sits in the default package, names that shim.
    fn shim_reference(&self) -> String {
        if self.package.is_empty() {
            self.shim_name()
        } else {
            format!("{}.{}", self.package, self.shim_name())
        }
    }
}

/// Every `#[test]` method in one lowering, in the order the files were lowered.
#[derive(Debug, Default)]
pub(crate) struct TestCatalog {
    tests: Vec<DiscoveredTest>,
}

impl TestCatalog {
    /// Collect the tests one parsed file declares.
    ///
    /// `hosts` comes from [`jals_syntax::cfg::CfgMap`], which has already rejected any `#[test]`
    /// whose shape or surroundings a harness could not call — so everything reaching here is
    /// nameable, and the walk only has to *build* the name.
    pub(crate) fn extend_from_file(&mut self, parse: &Parse, hosts: &[TestHost]) {
        if hosts.is_empty() {
            return;
        }
        let package = SourceFile::cast(parse.syntax())
            .and_then(|file| file.package())
            .and_then(|decl| decl.name())
            .map(|name| name.text());
        for host in hosts {
            let Some(method) = Self::method_name(&host.host) else {
                continue;
            };
            let Some(class) = Self::declaring_class(&host.host) else {
                continue;
            };
            self.tests.push(DiscoveredTest {
                package: package.clone().unwrap_or_default(),
                class,
                method,
                ignore: host.ignore,
                should_fail: host.should_fail,
            });
        }
    }

    /// The method's declared name.
    fn method_name(host: &SyntaxNode) -> Option<String> {
        jals_syntax::ast::MethodDecl::cast(host.clone()).and_then(|method| method.name())
    }

    /// The nested type chain declaring `host`, outermost first, dotted.
    ///
    /// `cfg` validation guarantees the chain is types all the way to the file, so a missing name
    /// here is recovery debris rather than a shape to diagnose a second time.
    fn declaring_class(host: &SyntaxNode) -> Option<String> {
        let mut names: Vec<String> = Vec::new();
        for node in host.ancestors() {
            if !Self::is_type_decl(node.kind()) {
                continue;
            }
            // A named type with no readable name is recovery debris. Failing the whole walk is
            // right: half a chain would name a class that does not exist.
            names.push(Self::type_name(&node)?);
        }
        if names.is_empty() {
            return None;
        }
        names.reverse();
        Some(names.join("."))
    }

    /// Whether `kind` declares a type that can hold a method.
    const fn is_type_decl(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            SyntaxKind::CLASS_DECL
                | SyntaxKind::INTERFACE_DECL
                | SyntaxKind::ENUM_DECL
                | SyntaxKind::RECORD_DECL
                | SyntaxKind::ANNOTATION_TYPE_DECL
        )
    }

    /// The declared name of a type node, for a node [`is_type_decl`](Self::is_type_decl) accepted.
    fn type_name(node: &SyntaxNode) -> Option<String> {
        use jals_syntax::ast::{
            AnnotationTypeDecl, ClassDecl, EnumDecl, InterfaceDecl, RecordDecl,
        };
        match node.kind() {
            SyntaxKind::CLASS_DECL => ClassDecl::cast(node.clone())?.name(),
            SyntaxKind::INTERFACE_DECL => InterfaceDecl::cast(node.clone())?.name(),
            SyntaxKind::ENUM_DECL => EnumDecl::cast(node.clone())?.name(),
            SyntaxKind::RECORD_DECL => RecordDecl::cast(node.clone())?.name(),
            SyntaxKind::ANNOTATION_TYPE_DECL => AnnotationTypeDecl::cast(node.clone())?.name(),
            _ => None,
        }
    }

    /// Render the harness sources for this catalog: one shim per test class, plus the root
    /// harness.
    ///
    /// Returns nothing when the catalog is empty — a project with no test still lowers, and
    /// generating a harness with no entry would make `jals build` and `jals test` differ over a
    /// file that says nothing.
    pub(crate) fn render(&self) -> Vec<(RelativePath, Vec<u8>)> {
        if self.tests.is_empty() {
            return Vec::new();
        }
        // Canonical order, so the generated bytes are a function of the tests alone and not of the
        // order the files happened to be lowered in.
        let mut tests = self.tests.clone();
        tests.sort();
        tests.dedup();

        let mut out = Vec::new();
        // One shim per declaring class, over a list the sort above already grouped by it.
        for class in tests.chunk_by(|a, b| a.qualified_class() == b.qualified_class()) {
            if let Some(shim) = Self::render_shim(class) {
                out.push(shim);
            }
        }
        out.push(Self::render_root(&tests));
        out
    }

    /// The shim for one test class.
    fn render_shim(tests: &[DiscoveredTest]) -> Option<(RelativePath, Vec<u8>)> {
        let first = tests.first()?;
        let qualified = first.qualified_class();
        let shim_name = first.shim_name();
        // A nested class is called through its outer chain, exactly as source in the same package
        // would write it.
        let call_prefix = &first.class;
        let mut body = String::new();
        if !first.package.is_empty() {
            let _ = write!(body, "package {};\n\n", first.package);
        }
        let _ = write!(
            body,
            "// Generated by `jals test`. The entry points of {qualified}.\n\
             public final class {shim_name} {{\n\
             \x20   public static void run(String id) throws Throwable {{\n"
        );
        for test in tests {
            let id = test.id();
            let call = format!("{call_prefix}.{}();", test.method);
            if test.should_fail {
                let _ = write!(
                    body,
                    "\x20       if (id.equals(\"{id}\")) {{\n\
                     \x20           try {{ {call} }} catch (Throwable thrown) {{ return; }}\n\
                     \x20           throw new AssertionError(\"{id} was expected to fail\");\n\
                     \x20       }}\n"
                );
            } else {
                let _ = writeln!(
                    body,
                    "\x20       if (id.equals(\"{id}\")) {{ {call} return; }}"
                );
            }
        }
        body.push_str(
            "\x20       throw new IllegalArgumentException(id);\n\
             \x20   }\n\
             }\n",
        );
        let path = Self::path_for(&first.package, &shim_name)?;
        Some((path, body.into_bytes()))
    }

    /// The root harness: `main`, `--list`, and the routing table.
    fn render_root(tests: &[DiscoveredTest]) -> (RelativePath, Vec<u8>) {
        let mut body = String::new();
        let _ = write!(
            body,
            "// Generated by `jals test`. Run one or more test ids, or list them with \
             `{LIST_ARGUMENT}`.\n\
             public final class {HARNESS_CLASS} {{\n\
             \x20   public static void main(String[] args) throws Throwable {{\n\
             \x20       if (args.length > 0 && args[0].equals(\"{LIST_ARGUMENT}\")) {{\n"
        );
        for test in tests {
            let mut flags = Vec::new();
            if test.ignore {
                flags.push("ignore");
            }
            if test.should_fail {
                flags.push("should_fail");
            }
            let _ = writeln!(
                body,
                "\x20           System.out.println(\"{}\\t{}\");",
                test.id(),
                flags.join(",")
            );
        }
        let _ = write!(
            body,
            "\x20           return;\n\
             \x20       }}\n\
             \x20       boolean quiet = args.length > 0 && args[0].equals(\"{QUIET_ARGUMENT}\");\n\
             \x20       int first = quiet ? 1 : 0;\n\
             \x20       for (int i = first; i < args.length; i++) {{\n\
             \x20           run(args[i], quiet);\n\
             \x20       }}\n\
             \x20   }}\n\
             \n\
             \x20   private static void run(String id, boolean quiet) throws Throwable {{\n"
        );
        for test in tests {
            let id = test.id();
            let shim = test.shim_reference();
            let _ = write!(
                body,
                "\x20       if (id.equals(\"{id}\")) {{\n\
                 \x20           {shim}.run(id);\n\
                 \x20           if (!quiet) {{ System.out.println(\"{OK_SENTINEL}\\t{id}\"); }}\n\
                 \x20           return;\n\
                 \x20       }}\n"
            );
        }
        body.push_str(
            "\x20       throw new IllegalArgumentException(id);\n\
             \x20   }\n\
             }\n",
        );
        let path = RelativePath::parse(&format!("{GENERATED_ROOT}/{HARNESS_CLASS}.java"))
            .expect("the generated harness path is a valid relative path");
        (path, body.into_bytes())
    }

    /// The logical path a generated class is emitted at, mirroring its package.
    fn path_for(package: &str, class: &str) -> Option<RelativePath> {
        let mut path = String::from(GENERATED_ROOT);
        if !package.is_empty() {
            for segment in package.split('.') {
                path.push('/');
                path.push_str(segment);
            }
        }
        path.push('/');
        path.push_str(class);
        path.push_str(".java");
        RelativePath::parse(&path).ok()
    }
}
