import jals.build.Build;
import jals.build.Output;
import jals.build.Project;

/**
 * The build script this example demonstrates, in the Java a `build.java` is written in.
 *
 * <p>Everything here is a static call on one of the `jals.build` classes: there is no compile
 * classpath to configure, no entry point to register, and no host object to receive — the script
 * engine links this file against `jals.build` and `java.base` and runs `main`. What the calls do
 * is collect directives; nothing is written, and nothing is compiled, until `main` returns without
 * a reported error.
 */
@SuppressWarnings("naming-convention")
class build {

    public static void main() {
        if (!Project.exists("src/main/java/Main.java")) {
            Build.error("expected src/main/java/Main.java");
        }

        // `writeText` answers with the project-relative key it wrote, which is what `addSource`
        // wants: the two calls are one generated source, not two strings that have to agree.
        String generated =
            Output.writeText(
                "generated/BuildInfo.java",
                "public final class BuildInfo {\n"
                    + "    private BuildInfo() {}\n"
                    + "    public static final String MESSAGE = \"generated by build.java\";\n"
                    + "}\n");
        Build.addSource(generated);

        Build.addJavacArg("-Xlint:all");
        Build.addJvmArg("-Djals.build.script=java");
        Build.setCompileEnv("JALS_GENERATOR", "java");
        Build.setRunEnv("JALS_BUILD_SCRIPT", "java");
        Build.rerunIfChanged("src/main/java/Main.java");
        Build.rerunIfEnvChanged("JALS_EXAMPLE_INPUT");
        Build.metadata("example", "java-build-script");
        Build.warning("generated BuildInfo.java");
    }
}
