//! The `examples` task: build — and, where the project declares an entry point, run — every
//! project under `examples/`, exactly as its README documents.
//!
//! The examples are the only place the whole `jals.toml` → build script → task DAG →
//! `javac`/`java` path runs end to end against a real JDK, so CI exercises them rather than only
//! compiling the workspace. `EXAMPLES` is the single list: the offline CI cell takes every entry
//! whose `network` is false and the networked cell takes the rest, so an example added here is
//! covered by one of the two without editing `.github/workflows/ci.yml`.
//!
//! Two examples deliberately ship without their input archive — both READMEs say "supply a JAR
//! containing …", and both destinations are `.gitignore`d, because what they demonstrate is the
//! task DAG rather than the archive's contents. `Fixture` builds that archive with the JDK's own
//! `javac`/`jar` before the example runs, which is the same thing a reader following the README
//! does by hand.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail, ensure};

/// Every example, in the order the task runs them.
///
/// A `stdout` of `&[]` is an assertion, not a gap: `jals-cli`'s reporter writes every diagnostic
/// to stderr, so a `build` that prints anything at all on stdout is a change worth failing on.
const EXAMPLES: &[Example] = &[
    Example {
        name: "hello_world",
        dir: "hello_world",
        fixtures: &[],
        network: false,
        steps: &[
            Step {
                args: &["build"],
                stdout: &[],
            },
            Step {
                args: &["run"],
                stdout: &["Hello, world!"],
            },
            // The README's second invocation: program arguments reach `main(String[])`.
            Step {
                args: &["run", "--", "Ada", "Linus"],
                stdout: &["Hello, Ada!", "Hello, Linus!"],
            },
        ],
    },
    Example {
        name: "rhai_build_script",
        dir: "rhai_build_script",
        fixtures: &[],
        network: false,
        // The three lines are the three halves of the script's contribution: a generated source,
        // a `-D` JVM argument, and a run-environment entry.
        steps: &[Step {
            args: &["run"],
            stdout: &["generated by build.rhai", "rhai", "rhai"],
        }],
    },
    Example {
        name: "task_source_archive",
        dir: "task_source_archive",
        fixtures: &[Fixture {
            jar: "task_source_archive/vendor/example-sources.jar",
            sources: &[("net/example/Generated.java", GENERATED_JAVA)],
            classes: false,
        }],
        network: false,
        // Build only: `Main` declares a field of the extracted type and no `main` method, so the
        // manifest's `[run] main-class` is what `jals run` would target, not something to run.
        steps: &[Step {
            args: &["build"],
            stdout: &[],
        }],
    },
    Example {
        name: "task_dependency",
        // The README's `cd consumer && jals run`: the library is never built directly, its task
        // DAG runs because the consumer depends on it.
        dir: "task_dependency/consumer",
        fixtures: &[Fixture {
            jar: "task_dependency/library/vendor/example.jar",
            sources: &[("net/example/Greeter.java", GREETER_JAVA)],
            // Both halves: the classes reach the consumer's compile classpath, the sources reach
            // it as navigation trees under the `sources` feature.
            classes: true,
        }],
        network: false,
        steps: &[Step {
            args: &["run"],
            stdout: &[GREETING],
        }],
    },
    // The two networked examples. Neither declares `[run]`: the SDK is something to depend on and
    // the mod is a jar to load, so both are build-only.
    Example {
        name: "minecraft",
        dir: "minecraft",
        fixtures: &[],
        network: true,
        // No feature flags, so this is the manifest's own default selection — the newest release,
        // which ships deobfuscated and skips the remap step. The 43-release axis is deliberately
        // not swept: every version is another full jar download.
        steps: &[Step {
            args: &["build"],
            stdout: &[],
        }],
    },
    Example {
        name: "minecraft_mod",
        dir: "minecraft_mod",
        fixtures: &[],
        network: true,
        steps: &[Step {
            args: &["build"],
            stdout: &[],
        }],
    },
];

/// The type `task_source_archive`'s `Main` declares a field of. Extracted from the archive into
/// `src/main/java/net/example`, so `javac` compiles it alongside the authored source.
const GENERATED_JAVA: &str = r"package net.example;

public final class Generated {
    private Generated() {}
}
";

/// What `task_dependency`'s consumer prints, and therefore the one string its fixture and its
/// expected stdout both have to spell.
const GREETING: &str = "Hello from the task-built library!";

/// The type `task_dependency`'s consumer compiles against (from the archive's `.class`) and can
/// navigate into (from its `.java`).
const GREETER_JAVA: &str = r#"package net.example;

public final class Greeter {
    private Greeter() {}

    public static String greeting() {
        return "Hello from the task-built library!";
    }
}
"#;

/// Which half of `EXAMPLES` to run, and against which `jals` build.
pub(crate) struct Options {
    /// Selects between the offline and the networked halves of `EXAMPLES`.
    pub(crate) network: Network,
    /// Run only these examples (by `Example::name`); empty runs whatever `network` admits.
    pub(crate) only: Vec<String>,
    /// Build the CLI with `--release`. Worth it for the networked examples, whose decompile and
    /// remap steps dominate the run; not worth the compile for the offline ones.
    pub(crate) release: bool,
}

/// How an example's `network` flag is read.
#[derive(Clone, Copy)]
pub(crate) enum Network {
    /// Run every example.
    Include,
    /// Run only the examples that fetch nothing.
    Skip,
    /// Run only the examples that fetch.
    Only,
}

/// One example project and the invocations that make up its documented flow.
struct Example {
    /// Selector for `--only`, and the heading printed as the example runs.
    name: &'static str,
    /// Directory `jals` is invoked in, relative to `examples/`.
    dir: &'static str,
    /// Archives to materialize before the first step.
    fixtures: &'static [Fixture],
    /// Whether the build fetches over the network.
    network: bool,
    /// The `jals` invocations, in order.
    steps: &'static [Step],
}

/// A `jals` invocation and the stdout it must produce.
struct Step {
    /// Arguments after `jals`.
    args: &'static [&'static str],
    /// The complete expected stdout, line by line.
    stdout: &'static [&'static str],
}

/// An input archive an example reads but the repository does not carry.
struct Fixture {
    /// Where the example's build script reads it, relative to `examples/`.
    jar: &'static str,
    /// The `.java` members: path inside the archive, and the source text.
    sources: &'static [(&'static str, &'static str)],
    /// Also compile every source and store the resulting `.class` alongside it. A task that only
    /// extracts sources needs the `.java`; one that puts the archive on a classpath needs both.
    classes: bool,
}

/// The task's orchestration: building the CLI once, then driving each selected example.
pub(crate) struct Examples;

impl Examples {
    /// Runs the selected examples, failing on the first one that does not behave as documented.
    pub(crate) fn run(options: &Options) -> Result<()> {
        let root = Self::project_root();
        let examples = root.join("examples");
        let selected = Self::select(options)?;
        let jals = Self::build_cli(&root, options.release)?;

        for example in &selected {
            println!("=== examples/{}", example.dir);
            example.execute(&examples, &jals)?;
        }
        println!("{} example(s) behaved as documented", selected.len());
        Ok(())
    }

    /// The examples `options` admits, in table order.
    fn select(options: &Options) -> Result<Vec<&'static Example>> {
        for name in &options.only {
            ensure!(
                EXAMPLES.iter().any(|example| example.name == *name),
                "no example named `{name}`"
            );
        }
        let selected: Vec<&Example> = EXAMPLES
            .iter()
            .filter(|example| match options.network {
                Network::Include => true,
                Network::Skip => !example.network,
                Network::Only => example.network,
            })
            .filter(|example| {
                options.only.is_empty() || options.only.iter().any(|n| n == example.name)
            })
            .collect();
        ensure!(!selected.is_empty(), "the selection matched no example");
        Ok(selected)
    }

    /// The workspace root (the parent of the `xtask` crate).
    fn project_root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("xtask lives directly under the project root")
            .to_path_buf()
    }

    /// Builds `jals` once and returns the binary. Every step then runs the binary directly, so a
    /// run of the whole table pays for one cargo invocation rather than one per step.
    fn build_cli(root: &Path, release: bool) -> Result<PathBuf> {
        let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
        let mut command = Command::new(&cargo);
        command
            .current_dir(root)
            .args(["build", "--package", "jals-cli"]);
        if release {
            command.arg("--release");
        }
        let status = command.status().context("failed to run cargo")?;
        ensure!(status.success(), "building the jals CLI failed");

        // `CARGO_TARGET_DIR` may be relative, in which case cargo reads it relative to the
        // workspace root — which is the directory the build above ran in.
        let target = std::env::var_os("CARGO_TARGET_DIR")
            .map_or_else(|| root.join("target"), |dir| root.join(dir));
        let binary = target
            .join(if release { "release" } else { "debug" })
            .join(if cfg!(windows) { "jals.exe" } else { "jals" });
        ensure!(
            binary.is_file(),
            "expected the jals binary at {}",
            binary.display()
        );
        Ok(binary)
    }

    /// A JDK tool, preferring `JAVA_HOME` over `PATH` so the fixtures are built with the same JDK
    /// `jals` will discover for the compile that consumes them.
    fn jdk_tool(name: &str) -> PathBuf {
        let file = if cfg!(windows) {
            format!("{name}.exe")
        } else {
            name.to_owned()
        };
        match std::env::var_os("JAVA_HOME") {
            Some(home) if !home.is_empty() => Path::new(&home).join("bin").join(file),
            _ => PathBuf::from(file),
        }
    }

    /// Runs `command`, failing with its stderr attached.
    fn check(command: &mut Command, what: &str) -> Result<()> {
        let output = command
            .output()
            .with_context(|| format!("failed to run {what}"))?;
        ensure!(
            output.status.success(),
            "{what} failed ({}):\n{}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim_end()
        );
        Ok(())
    }
}

impl Example {
    /// Materializes the fixtures, runs every step, then cleans up.
    fn execute(&self, examples: &Path, jals: &Path) -> Result<()> {
        let dir = examples.join(self.dir);
        ensure!(
            dir.join("jals.toml").is_file(),
            "{} has no jals.toml",
            dir.display()
        );
        for fixture in self.fixtures {
            fixture.materialize(examples)?;
        }
        for step in self.steps {
            step.execute(&dir, jals)?;
        }
        self.teardown(&dir, jals)
    }

    /// `jals clean`, both to leave the tree as the example ships it and because removing
    /// `classes-dir` and every `replace-root` publication is itself part of what the examples
    /// document. Its stdout is a list of absolute paths, so the check is on what survived rather
    /// than on what it printed.
    ///
    /// The fixture archives stay: they are `.gitignore`d, and keeping them makes a local re-run
    /// idempotent.
    fn teardown(&self, dir: &Path, jals: &Path) -> Result<()> {
        Examples::check(
            Command::new(jals).current_dir(dir).arg("clean"),
            "`jals clean`",
        )?;
        let classes = dir.join("target").join("classes");
        ensure!(!classes.exists(), "`jals clean` left {}", classes.display());
        Ok(())
    }
}

impl Step {
    /// Runs the step and compares its stdout with the documented output.
    fn execute(&self, dir: &Path, jals: &Path) -> Result<()> {
        let rendered = format!("jals {}", self.args.join(" "));
        println!("--- {rendered}");
        let output = Command::new(jals)
            .current_dir(dir)
            .args(self.args)
            .output()
            .with_context(|| format!("failed to run `{rendered}`"))?;
        let stderr = String::from_utf8_lossy(&output.stderr);
        ensure!(
            output.status.success(),
            "`{rendered}` in {} failed ({}):\n{}",
            dir.display(),
            output.status,
            stderr.trim_end()
        );

        let stdout = String::from_utf8_lossy(&output.stdout);
        // `str::lines` strips the `\r` of a `\r\n`, so the comparison is the same on Windows.
        let actual: Vec<&str> = stdout.lines().collect();
        if actual != self.stdout {
            bail!(
                "`{rendered}` in {} printed:\n{}\nexpected:\n{}",
                dir.display(),
                actual.join("\n"),
                self.stdout.join("\n")
            );
        }
        Ok(())
    }
}

impl Fixture {
    /// javac `--release` for the compiled members: the projects that consume this archive build
    /// with jals's own default release, and `javac` cannot read a class file newer than the
    /// `--release` it was given.
    const RELEASE: &'static str = "21";

    /// Writes the sources into a staging directory, compiles them when the archive needs classes,
    /// and packages the whole directory as the jar the example reads.
    fn materialize(&self, examples: &Path) -> Result<()> {
        let jar = examples.join(self.jar);
        let parent = jar
            .parent()
            .with_context(|| format!("fixture path {} has no parent", jar.display()))?;
        let staging = parent.join(".staging");
        if staging.exists() {
            fs::remove_dir_all(&staging)
                .with_context(|| format!("failed to clear {}", staging.display()))?;
        }

        let mut sources = Vec::new();
        for (path, text) in self.sources {
            let file = staging.join(path);
            let dir = file
                .parent()
                .with_context(|| format!("fixture member {path} has no parent"))?;
            fs::create_dir_all(dir)
                .with_context(|| format!("failed to create {}", dir.display()))?;
            fs::write(&file, text)
                .with_context(|| format!("failed to write {}", file.display()))?;
            sources.push((*path).to_owned());
        }

        if self.classes {
            let mut javac = Command::new(Examples::jdk_tool("javac"));
            javac
                .current_dir(&staging)
                .args(["--release", Self::RELEASE, "-d", "."])
                .args(&sources);
            Examples::check(&mut javac, "javac (fixture)")?;
        }

        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
        let mut jar_tool = Command::new(Examples::jdk_tool("jar"));
        jar_tool
            .args(["--create", "--file"])
            .arg(&jar)
            .args(["-C", "."])
            .arg(".");
        jar_tool.current_dir(&staging);
        Examples::check(&mut jar_tool, "jar (fixture)")?;

        fs::remove_dir_all(&staging)
            .with_context(|| format!("failed to remove {}", staging.display()))?;
        println!("--- fixture examples/{}", self.jar);
        Ok(())
    }
}
