#!/usr/bin/env python3
"""Write the `client-test` runtime block of `examples/minecraft_mod/build.rhai`.

A Rhai build script cannot walk a release's `libraries` array: `tasks.fetch_json` returns a *task
handle* and the fetch happens after the script has finished, so `tasks.json_at` projects one named
field and there is no index, no length and no loop. The list of jars a client needs therefore has to
be written out, and writing 60 of them by hand — each with its SHA-1 and its byte count — is not
maintenance anybody would keep up. This does it.

Three judgements live here rather than in the manifest:

* **Platform.** A library entry carries `rules` that admit it per operating system; this evaluates
  them for linux/x86_64 and nothing else. The example says so, and says why: the boot needs a GL
  stack, and CI has one on linux only.
* **Natives.** The `-natives-linux` classifier jars go on the *classpath* rather than being unpacked
  to a directory. LWJGL's own `SharedLibraryLoader` extracts them from there, so `java.library.path`
  never has to be set and jals needs no notion of a runtime directory. Measured, not assumed — the
  client boots with no `-Djava.library.path` at all.
* **Byte budget.** `fetch_jar` takes the size the release metadata states. The digest is what makes
  the bytes right; the count is what stops a redirect to something enormous.

Usage:

    python3 examples/scripts/gen-client-runtime.py 1.21.11

Re-run it when the pinned release changes. The result is committed — this is not a build step, and
CI never runs it.
"""

from __future__ import annotations

import json
import pathlib
import sys
import urllib.request

MANIFEST = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"
BEGIN = "    // <<< generated by examples/scripts/gen-client-runtime.py — do not edit by hand"
END = "    // >>> end generated"
SCRIPT = pathlib.Path(__file__).resolve().parents[1] / "minecraft_mod" / "build.rhai"


class Runtime:
    """The libraries one release needs on linux/x86_64."""

    def __init__(self, release: str) -> None:
        self.release = release
        manifest = self.get_json(MANIFEST)
        entry = next(v for v in manifest["versions"] if v["id"] == release)
        self.meta = self.get_json(entry["url"])

    @staticmethod
    def get_json(url: str) -> dict:
        with urllib.request.urlopen(url) as response:
            return json.load(response)

    @staticmethod
    def admits_linux(rules: list | None) -> bool:
        """Evaluate a library's `rules` for linux/x86_64.

        Last matching rule wins, as the launcher reads them. A rule keyed on `features` is a
        launcher toggle (demo mode, a custom resolution) that this runtime never sets, so it never
        matches.
        """
        if not rules:
            return True
        verdict = False
        for rule in rules:
            if "features" in rule:
                continue
            operating_system = rule.get("os", {})
            if operating_system.get("name", "linux") != "linux":
                continue
            if operating_system.get("arch", "x86_64") not in ("x86_64", "x64"):
                continue
            verdict = rule["action"] == "allow"
        return verdict

    def entries(self) -> list[tuple[str, str, str, int]]:
        """`(name, url, sha1, size)` for every admitted library, in metadata order."""
        admitted = []
        for library in self.meta["libraries"]:
            if not self.admits_linux(library.get("rules")):
                continue
            artifact = library.get("downloads", {}).get("artifact")
            if artifact is None:
                continue
            admitted.append(
                (
                    library["name"],
                    artifact["url"],
                    artifact["sha1"],
                    artifact["size"],
                )
            )
        return admitted

    def render(self) -> str:
        """The Rhai body between the markers."""
        lines = [
            f"    // {self.release}, linux/x86_64. The `-natives-linux` jars are on the classpath",
            "    // like every other one: LWJGL extracts what it needs out of them itself, so no",
            "    // `java.library.path` and no unpacked directory are involved.",
        ]
        for name, url, sha1, size in self.entries():
            lines.append(f"    // {name}")
            lines.append("    tasks.add_classpath(tasks.fetch_jar(")
            lines.append(f'        tasks.https_url("{url}"),')
            lines.append(f'        tasks.sha1("{sha1}"), tasks.bytes({size})));')
        return "\n".join(lines)

    def write(self, script: pathlib.Path) -> None:
        text = script.read_text(encoding="utf-8")
        begin = text.index(BEGIN) + len(BEGIN)
        end = text.index(END)
        script.write_text(text[:begin] + "\n" + self.render() + "\n" + text[end:], encoding="utf-8")


class Main:
    @staticmethod
    def run(argv: list[str]) -> int:
        release = argv[1] if len(argv) > 1 else "1.21.11"
        runtime = Runtime(release)
        runtime.write(SCRIPT)
        count = len(runtime.entries())
        print(f"wrote {count} libraries for {release} into {SCRIPT}")
        print(f'asset index is "{runtime.meta["assetIndex"]["id"]}" — the harness writes an empty one')
        return 0


if __name__ == "__main__":
    sys.exit(Main.run(sys.argv))
