//! GENERATED by `cargo run -p xtask -- codegen` from `java.ungram` — do not edit.

// @generated

use alloc::string::String;

use rowan::ast::{AstChildren, AstNode, support};

use super::name_text;
use crate::language::{JavaLanguage, SyntaxNode};
use crate::syntax_kind::SyntaxKind::{
    self, ANNOTATION, ANNOTATION_ARG_LIST, ANNOTATION_PAIR, ANNOTATION_TYPE_DECL, ARG_LIST,
    ARRAY_INIT, ASSERT_STMT, ASSIGNMENT_EXPR, BINARY_EXPR, BLOCK, BREAK_STMT, CALL_EXPR, CAST_EXPR,
    CATCH_CLAUSE, CLASS_BODY, CLASS_DECL, CLASS_LITERAL, CONSTRUCTOR_DECL, CONTINUE_STMT,
    DEFAULT_KW, DO_WHILE_STMT, EMPTY_STMT, ENUM_BODY, ENUM_CONSTANT, ENUM_DECL, EXPORTS_DIRECTIVE,
    EXPR_STMT, EXTENDS_CLAUSE, FIELD_ACCESS, FIELD_DECL, FINALLY_CLAUSE, FOR_EACH_STMT, FOR_STMT,
    GUARD, IF_STMT, IMPLEMENTS_CLAUSE, IMPORT_DECL, INDEX_EXPR, INITIALIZER, INTERFACE_DECL,
    LABELED_STMT, LAMBDA_EXPR, LAMBDA_PARAMS, LITERAL, LOCAL_VAR_DECL, METHOD_DECL,
    METHOD_REF_EXPR, MODIFIERS, MODULE_BODY, MODULE_DECL, MODULE_KW, NAME_REF, NEW_EXPR, OPEN_KW,
    OPENS_DIRECTIVE, PACKAGE_DECL, PARAM, PARAM_LIST, PAREN_EXPR, PERMITS_CLAUSE, POSTFIX_EXPR,
    PROVIDES_DIRECTIVE, QUALIFIED_NAME, RECORD_COMPONENT, RECORD_DECL, RECORD_HEADER,
    RECORD_PATTERN, REQUIRES_DIRECTIVE, RESOURCE, RESOURCE_LIST, RETURN_STMT, SEALED_KW,
    SOURCE_FILE, STAR, STATIC_KW, SWITCH_BLOCK, SWITCH_EXPR, SWITCH_GROUP, SWITCH_LABEL,
    SWITCH_RULE, SWITCH_STMT, SYNCHRONIZED_STMT, TERNARY_EXPR, THROW_STMT, THROWS_CLAUSE,
    TRANSITIVE_KW, TRY_STMT, TYPE, TYPE_ARGS, TYPE_PARAM, TYPE_PARAMS, TYPE_PATTERN, UNARY_EXPR,
    UNNAMED_PATTERN, USES_DIRECTIVE, WHILE_STMT, YIELD_STMT,
};

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SourceFile {
    pub(crate) syntax: SyntaxNode,
}

impl SourceFile {
    pub fn package(&self) -> Option<PackageDecl> {
        support::child(&self.syntax)
    }
    pub fn imports(&self) -> AstChildren<ImportDecl> {
        support::children(&self.syntax)
    }
    pub fn module(&self) -> Option<ModuleDecl> {
        support::child(&self.syntax)
    }
    pub fn decls(&self) -> AstChildren<Decl> {
        support::children(&self.syntax)
    }
}

impl AstNode for SourceFile {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SOURCE_FILE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct PackageDecl {
    pub(crate) syntax: SyntaxNode,
}

impl PackageDecl {
    pub fn name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
}

impl AstNode for PackageDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == PACKAGE_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ImportDecl {
    pub(crate) syntax: SyntaxNode,
}

impl ImportDecl {
    pub fn is_static(&self) -> bool {
        support::token(&self.syntax, STATIC_KW).is_some()
    }
    pub fn is_module(&self) -> bool {
        support::token(&self.syntax, MODULE_KW).is_some()
    }
    pub fn name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
}

impl AstNode for ImportDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == IMPORT_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ModuleDecl {
    pub(crate) syntax: SyntaxNode,
}

impl ModuleDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn is_open(&self) -> bool {
        support::token(&self.syntax, OPEN_KW).is_some()
    }
    pub fn name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<ModuleBody> {
        support::child(&self.syntax)
    }
}

impl AstNode for ModuleDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == MODULE_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Decl {
    Class(ClassDecl),
    Interface(InterfaceDecl),
    Enum(EnumDecl),
    Record(RecordDecl),
    AnnotationType(AnnotationTypeDecl),
    Method(MethodDecl),
    Field(FieldDecl),
}

impl AstNode for Decl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            CLASS_DECL
                | INTERFACE_DECL
                | ENUM_DECL
                | RECORD_DECL
                | ANNOTATION_TYPE_DECL
                | METHOD_DECL
                | FIELD_DECL
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        let res = match syntax.kind() {
            CLASS_DECL => Self::Class(ClassDecl { syntax }),
            INTERFACE_DECL => Self::Interface(InterfaceDecl { syntax }),
            ENUM_DECL => Self::Enum(EnumDecl { syntax }),
            RECORD_DECL => Self::Record(RecordDecl { syntax }),
            ANNOTATION_TYPE_DECL => Self::AnnotationType(AnnotationTypeDecl { syntax }),
            METHOD_DECL => Self::Method(MethodDecl { syntax }),
            FIELD_DECL => Self::Field(FieldDecl { syntax }),
            _ => return None,
        };
        Some(res)
    }
    fn syntax(&self) -> &SyntaxNode {
        match self {
            Self::Class(it) => it.syntax(),
            Self::Interface(it) => it.syntax(),
            Self::Enum(it) => it.syntax(),
            Self::Record(it) => it.syntax(),
            Self::AnnotationType(it) => it.syntax(),
            Self::Method(it) => it.syntax(),
            Self::Field(it) => it.syntax(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct QualifiedName {
    pub(crate) syntax: SyntaxNode,
}

impl QualifiedName {
    pub fn is_wildcard(&self) -> bool {
        support::token(&self.syntax, STAR).is_some()
    }
}

impl AstNode for QualifiedName {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == QUALIFIED_NAME
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Modifiers {
    pub(crate) syntax: SyntaxNode,
}

impl Modifiers {
    pub fn annotations(&self) -> AstChildren<Annotation> {
        support::children(&self.syntax)
    }
    pub fn is_sealed(&self) -> bool {
        support::token(&self.syntax, SEALED_KW).is_some()
    }
}

impl AstNode for Modifiers {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == MODIFIERS
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ModuleBody {
    pub(crate) syntax: SyntaxNode,
}

impl ModuleBody {
    pub fn directives(&self) -> AstChildren<Directive> {
        support::children(&self.syntax)
    }
}

impl AstNode for ModuleBody {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == MODULE_BODY
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Directive {
    Requires(RequiresDirective),
    Exports(ExportsDirective),
    Opens(OpensDirective),
    Uses(UsesDirective),
    Provides(ProvidesDirective),
}

impl AstNode for Directive {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            REQUIRES_DIRECTIVE
                | EXPORTS_DIRECTIVE
                | OPENS_DIRECTIVE
                | USES_DIRECTIVE
                | PROVIDES_DIRECTIVE
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        let res = match syntax.kind() {
            REQUIRES_DIRECTIVE => Self::Requires(RequiresDirective { syntax }),
            EXPORTS_DIRECTIVE => Self::Exports(ExportsDirective { syntax }),
            OPENS_DIRECTIVE => Self::Opens(OpensDirective { syntax }),
            USES_DIRECTIVE => Self::Uses(UsesDirective { syntax }),
            PROVIDES_DIRECTIVE => Self::Provides(ProvidesDirective { syntax }),
            _ => return None,
        };
        Some(res)
    }
    fn syntax(&self) -> &SyntaxNode {
        match self {
            Self::Requires(it) => it.syntax(),
            Self::Exports(it) => it.syntax(),
            Self::Opens(it) => it.syntax(),
            Self::Uses(it) => it.syntax(),
            Self::Provides(it) => it.syntax(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct RequiresDirective {
    pub(crate) syntax: SyntaxNode,
}

impl RequiresDirective {
    pub fn is_transitive(&self) -> bool {
        support::token(&self.syntax, TRANSITIVE_KW).is_some()
    }
    pub fn is_static(&self) -> bool {
        support::token(&self.syntax, STATIC_KW).is_some()
    }
    pub fn module_name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
}

impl AstNode for RequiresDirective {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == REQUIRES_DIRECTIVE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ExportsDirective {
    pub(crate) syntax: SyntaxNode,
}

impl ExportsDirective {
    pub fn package_name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
}

impl AstNode for ExportsDirective {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == EXPORTS_DIRECTIVE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct OpensDirective {
    pub(crate) syntax: SyntaxNode,
}

impl OpensDirective {
    pub fn package_name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
}

impl AstNode for OpensDirective {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == OPENS_DIRECTIVE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct UsesDirective {
    pub(crate) syntax: SyntaxNode,
}

impl UsesDirective {
    pub fn type_name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
}

impl AstNode for UsesDirective {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == USES_DIRECTIVE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ProvidesDirective {
    pub(crate) syntax: SyntaxNode,
}

impl ProvidesDirective {
    pub fn service(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
}

impl AstNode for ProvidesDirective {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == PROVIDES_DIRECTIVE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ClassDecl {
    pub(crate) syntax: SyntaxNode,
}

impl ClassDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn type_params(&self) -> Option<TypeParams> {
        support::child(&self.syntax)
    }
    pub fn extends_clause(&self) -> Option<ExtendsClause> {
        support::child(&self.syntax)
    }
    pub fn implements_clause(&self) -> Option<ImplementsClause> {
        support::child(&self.syntax)
    }
    pub fn permits_clause(&self) -> Option<PermitsClause> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<ClassBody> {
        support::child(&self.syntax)
    }
}

impl AstNode for ClassDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == CLASS_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct InterfaceDecl {
    pub(crate) syntax: SyntaxNode,
}

impl InterfaceDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn type_params(&self) -> Option<TypeParams> {
        support::child(&self.syntax)
    }
    pub fn extends_clause(&self) -> Option<ExtendsClause> {
        support::child(&self.syntax)
    }
    pub fn permits_clause(&self) -> Option<PermitsClause> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<ClassBody> {
        support::child(&self.syntax)
    }
}

impl AstNode for InterfaceDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == INTERFACE_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct EnumDecl {
    pub(crate) syntax: SyntaxNode,
}

impl EnumDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn implements_clause(&self) -> Option<ImplementsClause> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<EnumBody> {
        support::child(&self.syntax)
    }
}

impl AstNode for EnumDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ENUM_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct RecordDecl {
    pub(crate) syntax: SyntaxNode,
}

impl RecordDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn type_params(&self) -> Option<TypeParams> {
        support::child(&self.syntax)
    }
    pub fn header(&self) -> Option<RecordHeader> {
        support::child(&self.syntax)
    }
    pub fn implements_clause(&self) -> Option<ImplementsClause> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<ClassBody> {
        support::child(&self.syntax)
    }
}

impl AstNode for RecordDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == RECORD_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct AnnotationTypeDecl {
    pub(crate) syntax: SyntaxNode,
}

impl AnnotationTypeDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn body(&self) -> Option<ClassBody> {
        support::child(&self.syntax)
    }
}

impl AstNode for AnnotationTypeDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ANNOTATION_TYPE_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct MethodDecl {
    pub(crate) syntax: SyntaxNode,
}

impl MethodDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn type_params(&self) -> Option<TypeParams> {
        support::child(&self.syntax)
    }
    pub fn return_type(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn params(&self) -> Option<ParamList> {
        support::child(&self.syntax)
    }
    pub fn throws_clause(&self) -> Option<ThrowsClause> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}

impl AstNode for MethodDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == METHOD_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct FieldDecl {
    pub(crate) syntax: SyntaxNode,
}

impl FieldDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for FieldDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == FIELD_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct TypeParams {
    pub(crate) syntax: SyntaxNode,
}

impl TypeParams {
    pub fn params(&self) -> AstChildren<TypeParam> {
        support::children(&self.syntax)
    }
}

impl AstNode for TypeParams {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == TYPE_PARAMS
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ExtendsClause {
    pub(crate) syntax: SyntaxNode,
}

impl ExtendsClause {
    pub fn types(&self) -> AstChildren<Type> {
        support::children(&self.syntax)
    }
}

impl AstNode for ExtendsClause {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == EXTENDS_CLAUSE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ImplementsClause {
    pub(crate) syntax: SyntaxNode,
}

impl ImplementsClause {
    pub fn types(&self) -> AstChildren<Type> {
        support::children(&self.syntax)
    }
}

impl AstNode for ImplementsClause {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == IMPLEMENTS_CLAUSE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct PermitsClause {
    pub(crate) syntax: SyntaxNode,
}

impl PermitsClause {
    pub fn types(&self) -> AstChildren<Type> {
        support::children(&self.syntax)
    }
}

impl AstNode for PermitsClause {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == PERMITS_CLAUSE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ClassBody {
    pub(crate) syntax: SyntaxNode,
}

impl ClassBody {
    pub fn members(&self) -> AstChildren<Member> {
        support::children(&self.syntax)
    }
}

impl AstNode for ClassBody {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == CLASS_BODY
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct EnumBody {
    pub(crate) syntax: SyntaxNode,
}

impl EnumBody {
    pub fn constants(&self) -> AstChildren<EnumConstant> {
        support::children(&self.syntax)
    }
    pub fn members(&self) -> AstChildren<Member> {
        support::children(&self.syntax)
    }
}

impl AstNode for EnumBody {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ENUM_BODY
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct RecordHeader {
    pub(crate) syntax: SyntaxNode,
}

impl RecordHeader {
    pub fn components(&self) -> AstChildren<RecordComponent> {
        support::children(&self.syntax)
    }
}

impl AstNode for RecordHeader {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == RECORD_HEADER
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Annotation {
    pub(crate) syntax: SyntaxNode,
}

impl Annotation {
    pub fn name(&self) -> Option<QualifiedName> {
        support::child(&self.syntax)
    }
    pub fn args(&self) -> Option<AnnotationArgList> {
        support::child(&self.syntax)
    }
}

impl AstNode for Annotation {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ANNOTATION
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct AnnotationArgList {
    pub(crate) syntax: SyntaxNode,
}

impl AnnotationArgList {
    pub fn pairs(&self) -> AstChildren<AnnotationPair> {
        support::children(&self.syntax)
    }
}

impl AstNode for AnnotationArgList {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ANNOTATION_ARG_LIST
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct AnnotationPair {
    pub(crate) syntax: SyntaxNode,
}

impl AnnotationPair {
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for AnnotationPair {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ANNOTATION_PAIR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Expr {
    Literal(Literal),
    NameRef(NameRef),
    Binary(BinaryExpr),
    Unary(UnaryExpr),
    Postfix(PostfixExpr),
    Paren(ParenExpr),
    Call(CallExpr),
    FieldAccess(FieldAccess),
    Index(IndexExpr),
    New(NewExpr),
    Assignment(AssignmentExpr),
    Ternary(TernaryExpr),
    Lambda(LambdaExpr),
    MethodRef(MethodRefExpr),
    Cast(CastExpr),
    Switch(SwitchExpr),
    ClassLiteral(ClassLiteral),
    ArrayInit(ArrayInit),
}

impl AstNode for Expr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            LITERAL
                | NAME_REF
                | BINARY_EXPR
                | UNARY_EXPR
                | POSTFIX_EXPR
                | PAREN_EXPR
                | CALL_EXPR
                | FIELD_ACCESS
                | INDEX_EXPR
                | NEW_EXPR
                | ASSIGNMENT_EXPR
                | TERNARY_EXPR
                | LAMBDA_EXPR
                | METHOD_REF_EXPR
                | CAST_EXPR
                | SWITCH_EXPR
                | CLASS_LITERAL
                | ARRAY_INIT
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        let res = match syntax.kind() {
            LITERAL => Self::Literal(Literal { syntax }),
            NAME_REF => Self::NameRef(NameRef { syntax }),
            BINARY_EXPR => Self::Binary(BinaryExpr { syntax }),
            UNARY_EXPR => Self::Unary(UnaryExpr { syntax }),
            POSTFIX_EXPR => Self::Postfix(PostfixExpr { syntax }),
            PAREN_EXPR => Self::Paren(ParenExpr { syntax }),
            CALL_EXPR => Self::Call(CallExpr { syntax }),
            FIELD_ACCESS => Self::FieldAccess(FieldAccess { syntax }),
            INDEX_EXPR => Self::Index(IndexExpr { syntax }),
            NEW_EXPR => Self::New(NewExpr { syntax }),
            ASSIGNMENT_EXPR => Self::Assignment(AssignmentExpr { syntax }),
            TERNARY_EXPR => Self::Ternary(TernaryExpr { syntax }),
            LAMBDA_EXPR => Self::Lambda(LambdaExpr { syntax }),
            METHOD_REF_EXPR => Self::MethodRef(MethodRefExpr { syntax }),
            CAST_EXPR => Self::Cast(CastExpr { syntax }),
            SWITCH_EXPR => Self::Switch(SwitchExpr { syntax }),
            CLASS_LITERAL => Self::ClassLiteral(ClassLiteral { syntax }),
            ARRAY_INIT => Self::ArrayInit(ArrayInit { syntax }),
            _ => return None,
        };
        Some(res)
    }
    fn syntax(&self) -> &SyntaxNode {
        match self {
            Self::Literal(it) => it.syntax(),
            Self::NameRef(it) => it.syntax(),
            Self::Binary(it) => it.syntax(),
            Self::Unary(it) => it.syntax(),
            Self::Postfix(it) => it.syntax(),
            Self::Paren(it) => it.syntax(),
            Self::Call(it) => it.syntax(),
            Self::FieldAccess(it) => it.syntax(),
            Self::Index(it) => it.syntax(),
            Self::New(it) => it.syntax(),
            Self::Assignment(it) => it.syntax(),
            Self::Ternary(it) => it.syntax(),
            Self::Lambda(it) => it.syntax(),
            Self::MethodRef(it) => it.syntax(),
            Self::Cast(it) => it.syntax(),
            Self::Switch(it) => it.syntax(),
            Self::ClassLiteral(it) => it.syntax(),
            Self::ArrayInit(it) => it.syntax(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct TypeParam {
    pub(crate) syntax: SyntaxNode,
}

impl TypeParam {
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn bounds(&self) -> AstChildren<Type> {
        support::children(&self.syntax)
    }
}

impl AstNode for TypeParam {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == TYPE_PARAM
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Type {
    pub(crate) syntax: SyntaxNode,
}

impl Type {
    pub fn type_args(&self) -> Option<TypeArgs> {
        support::child(&self.syntax)
    }
}

impl AstNode for Type {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == TYPE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ThrowsClause {
    pub(crate) syntax: SyntaxNode,
}

impl ThrowsClause {
    pub fn types(&self) -> AstChildren<Type> {
        support::children(&self.syntax)
    }
}

impl AstNode for ThrowsClause {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == THROWS_CLAUSE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct RecordComponent {
    pub(crate) syntax: SyntaxNode,
}

impl RecordComponent {
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
}

impl AstNode for RecordComponent {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == RECORD_COMPONENT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Member {
    Field(FieldDecl),
    Method(MethodDecl),
    Constructor(ConstructorDecl),
    Initializer(Initializer),
    Class(ClassDecl),
    Interface(InterfaceDecl),
    Enum(EnumDecl),
    Record(RecordDecl),
    AnnotationType(AnnotationTypeDecl),
}

impl AstNode for Member {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            FIELD_DECL
                | METHOD_DECL
                | CONSTRUCTOR_DECL
                | INITIALIZER
                | CLASS_DECL
                | INTERFACE_DECL
                | ENUM_DECL
                | RECORD_DECL
                | ANNOTATION_TYPE_DECL
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        let res = match syntax.kind() {
            FIELD_DECL => Self::Field(FieldDecl { syntax }),
            METHOD_DECL => Self::Method(MethodDecl { syntax }),
            CONSTRUCTOR_DECL => Self::Constructor(ConstructorDecl { syntax }),
            INITIALIZER => Self::Initializer(Initializer { syntax }),
            CLASS_DECL => Self::Class(ClassDecl { syntax }),
            INTERFACE_DECL => Self::Interface(InterfaceDecl { syntax }),
            ENUM_DECL => Self::Enum(EnumDecl { syntax }),
            RECORD_DECL => Self::Record(RecordDecl { syntax }),
            ANNOTATION_TYPE_DECL => Self::AnnotationType(AnnotationTypeDecl { syntax }),
            _ => return None,
        };
        Some(res)
    }
    fn syntax(&self) -> &SyntaxNode {
        match self {
            Self::Field(it) => it.syntax(),
            Self::Method(it) => it.syntax(),
            Self::Constructor(it) => it.syntax(),
            Self::Initializer(it) => it.syntax(),
            Self::Class(it) => it.syntax(),
            Self::Interface(it) => it.syntax(),
            Self::Enum(it) => it.syntax(),
            Self::Record(it) => it.syntax(),
            Self::AnnotationType(it) => it.syntax(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct EnumConstant {
    pub(crate) syntax: SyntaxNode,
}

impl EnumConstant {
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn args(&self) -> Option<ArgList> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<ClassBody> {
        support::child(&self.syntax)
    }
}

impl AstNode for EnumConstant {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ENUM_CONSTANT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ArgList {
    pub(crate) syntax: SyntaxNode,
}

impl ArgList {
    pub fn args(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}

impl AstNode for ArgList {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ARG_LIST
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ConstructorDecl {
    pub(crate) syntax: SyntaxNode,
}

impl ConstructorDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn params(&self) -> Option<ParamList> {
        support::child(&self.syntax)
    }
    pub fn throws_clause(&self) -> Option<ThrowsClause> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}

impl AstNode for ConstructorDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == CONSTRUCTOR_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Initializer {
    pub(crate) syntax: SyntaxNode,
}

impl Initializer {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn block(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}

impl AstNode for Initializer {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == INITIALIZER
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ParamList {
    pub(crate) syntax: SyntaxNode,
}

impl ParamList {
    pub fn params(&self) -> AstChildren<Param> {
        support::children(&self.syntax)
    }
}

impl AstNode for ParamList {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == PARAM_LIST
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Block {
    pub(crate) syntax: SyntaxNode,
}

impl Block {
    pub fn stmts(&self) -> AstChildren<Stmt> {
        support::children(&self.syntax)
    }
}

impl AstNode for Block {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == BLOCK
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Param {
    pub(crate) syntax: SyntaxNode,
}

impl Param {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
}

impl AstNode for Param {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == PARAM
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct TypeArgs {
    pub(crate) syntax: SyntaxNode,
}

impl TypeArgs {
    pub fn args(&self) -> AstChildren<Type> {
        support::children(&self.syntax)
    }
}

impl AstNode for TypeArgs {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == TYPE_ARGS
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Stmt {
    LocalVar(LocalVarDecl),
    Block(Block),
    Expr(ExprStmt),
    Return(ReturnStmt),
    If(IfStmt),
    While(WhileStmt),
    DoWhile(DoWhileStmt),
    For(ForStmt),
    ForEach(ForEachStmt),
    Break(BreakStmt),
    Continue(ContinueStmt),
    Throw(ThrowStmt),
    Yield(YieldStmt),
    Assert(AssertStmt),
    Synchronized(SynchronizedStmt),
    Try(TryStmt),
    Switch(SwitchStmt),
    Labeled(LabeledStmt),
    Empty(EmptyStmt),
}

impl AstNode for Stmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            LOCAL_VAR_DECL
                | BLOCK
                | EXPR_STMT
                | RETURN_STMT
                | IF_STMT
                | WHILE_STMT
                | DO_WHILE_STMT
                | FOR_STMT
                | FOR_EACH_STMT
                | BREAK_STMT
                | CONTINUE_STMT
                | THROW_STMT
                | YIELD_STMT
                | ASSERT_STMT
                | SYNCHRONIZED_STMT
                | TRY_STMT
                | SWITCH_STMT
                | LABELED_STMT
                | EMPTY_STMT
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        let res = match syntax.kind() {
            LOCAL_VAR_DECL => Self::LocalVar(LocalVarDecl { syntax }),
            BLOCK => Self::Block(Block { syntax }),
            EXPR_STMT => Self::Expr(ExprStmt { syntax }),
            RETURN_STMT => Self::Return(ReturnStmt { syntax }),
            IF_STMT => Self::If(IfStmt { syntax }),
            WHILE_STMT => Self::While(WhileStmt { syntax }),
            DO_WHILE_STMT => Self::DoWhile(DoWhileStmt { syntax }),
            FOR_STMT => Self::For(ForStmt { syntax }),
            FOR_EACH_STMT => Self::ForEach(ForEachStmt { syntax }),
            BREAK_STMT => Self::Break(BreakStmt { syntax }),
            CONTINUE_STMT => Self::Continue(ContinueStmt { syntax }),
            THROW_STMT => Self::Throw(ThrowStmt { syntax }),
            YIELD_STMT => Self::Yield(YieldStmt { syntax }),
            ASSERT_STMT => Self::Assert(AssertStmt { syntax }),
            SYNCHRONIZED_STMT => Self::Synchronized(SynchronizedStmt { syntax }),
            TRY_STMT => Self::Try(TryStmt { syntax }),
            SWITCH_STMT => Self::Switch(SwitchStmt { syntax }),
            LABELED_STMT => Self::Labeled(LabeledStmt { syntax }),
            EMPTY_STMT => Self::Empty(EmptyStmt { syntax }),
            _ => return None,
        };
        Some(res)
    }
    fn syntax(&self) -> &SyntaxNode {
        match self {
            Self::LocalVar(it) => it.syntax(),
            Self::Block(it) => it.syntax(),
            Self::Expr(it) => it.syntax(),
            Self::Return(it) => it.syntax(),
            Self::If(it) => it.syntax(),
            Self::While(it) => it.syntax(),
            Self::DoWhile(it) => it.syntax(),
            Self::For(it) => it.syntax(),
            Self::ForEach(it) => it.syntax(),
            Self::Break(it) => it.syntax(),
            Self::Continue(it) => it.syntax(),
            Self::Throw(it) => it.syntax(),
            Self::Yield(it) => it.syntax(),
            Self::Assert(it) => it.syntax(),
            Self::Synchronized(it) => it.syntax(),
            Self::Try(it) => it.syntax(),
            Self::Switch(it) => it.syntax(),
            Self::Labeled(it) => it.syntax(),
            Self::Empty(it) => it.syntax(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct LocalVarDecl {
    pub(crate) syntax: SyntaxNode,
}

impl LocalVarDecl {
    pub fn modifiers(&self) -> Option<Modifiers> {
        support::child(&self.syntax)
    }
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn value(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for LocalVarDecl {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == LOCAL_VAR_DECL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ExprStmt {
    pub(crate) syntax: SyntaxNode,
}

impl ExprStmt {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for ExprStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == EXPR_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ReturnStmt {
    pub(crate) syntax: SyntaxNode,
}

impl ReturnStmt {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for ReturnStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == RETURN_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct IfStmt {
    pub(crate) syntax: SyntaxNode,
}

impl IfStmt {
    pub fn condition(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn branches(&self) -> AstChildren<Stmt> {
        support::children(&self.syntax)
    }
}

impl AstNode for IfStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == IF_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct WhileStmt {
    pub(crate) syntax: SyntaxNode,
}

impl WhileStmt {
    pub fn condition(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Stmt> {
        support::child(&self.syntax)
    }
}

impl AstNode for WhileStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == WHILE_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct DoWhileStmt {
    pub(crate) syntax: SyntaxNode,
}

impl DoWhileStmt {
    pub fn body(&self) -> Option<Stmt> {
        support::child(&self.syntax)
    }
    pub fn condition(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for DoWhileStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == DO_WHILE_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ForStmt {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ForStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == FOR_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ForEachStmt {
    pub(crate) syntax: SyntaxNode,
}

impl ForEachStmt {
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn iterable(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Stmt> {
        support::child(&self.syntax)
    }
}

impl AstNode for ForEachStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == FOR_EACH_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct BreakStmt {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for BreakStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == BREAK_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ContinueStmt {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ContinueStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == CONTINUE_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ThrowStmt {
    pub(crate) syntax: SyntaxNode,
}

impl ThrowStmt {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for ThrowStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == THROW_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct YieldStmt {
    pub(crate) syntax: SyntaxNode,
}

impl YieldStmt {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for YieldStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == YIELD_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct AssertStmt {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for AssertStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ASSERT_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SynchronizedStmt {
    pub(crate) syntax: SyntaxNode,
}

impl SynchronizedStmt {
    pub fn lock(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}

impl AstNode for SynchronizedStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SYNCHRONIZED_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct TryStmt {
    pub(crate) syntax: SyntaxNode,
}

impl TryStmt {
    pub fn resources(&self) -> Option<ResourceList> {
        support::child(&self.syntax)
    }
    pub fn block(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
    pub fn catches(&self) -> AstChildren<CatchClause> {
        support::children(&self.syntax)
    }
    pub fn finally(&self) -> Option<FinallyClause> {
        support::child(&self.syntax)
    }
}

impl AstNode for TryStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == TRY_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SwitchStmt {
    pub(crate) syntax: SyntaxNode,
}

impl SwitchStmt {
    pub fn selector(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<SwitchBlock> {
        support::child(&self.syntax)
    }
}

impl AstNode for SwitchStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SWITCH_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct LabeledStmt {
    pub(crate) syntax: SyntaxNode,
}

impl LabeledStmt {
    pub fn label(&self) -> Option<String> {
        name_text(&self.syntax)
    }
    pub fn stmt(&self) -> Option<Stmt> {
        support::child(&self.syntax)
    }
}

impl AstNode for LabeledStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == LABELED_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct EmptyStmt {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for EmptyStmt {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == EMPTY_STMT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ResourceList {
    pub(crate) syntax: SyntaxNode,
}

impl ResourceList {
    pub fn resources(&self) -> AstChildren<Resource> {
        support::children(&self.syntax)
    }
}

impl AstNode for ResourceList {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == RESOURCE_LIST
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct CatchClause {
    pub(crate) syntax: SyntaxNode,
}

impl CatchClause {
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn block(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}

impl AstNode for CatchClause {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == CATCH_CLAUSE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct FinallyClause {
    pub(crate) syntax: SyntaxNode,
}

impl FinallyClause {
    pub fn block(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
}

impl AstNode for FinallyClause {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == FINALLY_CLAUSE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Resource {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Resource {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == RESOURCE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SwitchBlock {
    pub(crate) syntax: SyntaxNode,
}

impl SwitchBlock {
    pub fn rules(&self) -> AstChildren<SwitchRule> {
        support::children(&self.syntax)
    }
    pub fn groups(&self) -> AstChildren<SwitchGroup> {
        support::children(&self.syntax)
    }
}

impl AstNode for SwitchBlock {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SWITCH_BLOCK
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SwitchRule {
    pub(crate) syntax: SyntaxNode,
}

impl SwitchRule {
    pub fn label(&self) -> Option<SwitchLabel> {
        support::child(&self.syntax)
    }
}

impl AstNode for SwitchRule {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SWITCH_RULE
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SwitchGroup {
    pub(crate) syntax: SyntaxNode,
}

impl SwitchGroup {
    pub fn labels(&self) -> AstChildren<SwitchLabel> {
        support::children(&self.syntax)
    }
    pub fn stmts(&self) -> AstChildren<Stmt> {
        support::children(&self.syntax)
    }
}

impl AstNode for SwitchGroup {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SWITCH_GROUP
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SwitchLabel {
    pub(crate) syntax: SyntaxNode,
}

impl SwitchLabel {
    pub fn is_default(&self) -> bool {
        support::token(&self.syntax, DEFAULT_KW).is_some()
    }
}

impl AstNode for SwitchLabel {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SWITCH_LABEL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Pattern {
    Type(TypePattern),
    Record(RecordPattern),
    Unnamed(UnnamedPattern),
}

impl AstNode for Pattern {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, TYPE_PATTERN | RECORD_PATTERN | UNNAMED_PATTERN)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        let res = match syntax.kind() {
            TYPE_PATTERN => Self::Type(TypePattern { syntax }),
            RECORD_PATTERN => Self::Record(RecordPattern { syntax }),
            UNNAMED_PATTERN => Self::Unnamed(UnnamedPattern { syntax }),
            _ => return None,
        };
        Some(res)
    }
    fn syntax(&self) -> &SyntaxNode {
        match self {
            Self::Type(it) => it.syntax(),
            Self::Record(it) => it.syntax(),
            Self::Unnamed(it) => it.syntax(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Guard {
    pub(crate) syntax: SyntaxNode,
}

impl Guard {
    pub fn condition(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for Guard {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == GUARD
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct TypePattern {
    pub(crate) syntax: SyntaxNode,
}

impl TypePattern {
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn name(&self) -> Option<String> {
        name_text(&self.syntax)
    }
}

impl AstNode for TypePattern {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == TYPE_PATTERN
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct RecordPattern {
    pub(crate) syntax: SyntaxNode,
}

impl RecordPattern {
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn components(&self) -> AstChildren<Pattern> {
        support::children(&self.syntax)
    }
}

impl AstNode for RecordPattern {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == RECORD_PATTERN
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct UnnamedPattern {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for UnnamedPattern {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == UNNAMED_PATTERN
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Literal {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Literal {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == LITERAL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct NameRef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for NameRef {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == NAME_REF
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct BinaryExpr {
    pub(crate) syntax: SyntaxNode,
}

impl BinaryExpr {
    pub fn operands(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}

impl AstNode for BinaryExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == BINARY_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct UnaryExpr {
    pub(crate) syntax: SyntaxNode,
}

impl UnaryExpr {
    pub fn operand(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for UnaryExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == UNARY_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct PostfixExpr {
    pub(crate) syntax: SyntaxNode,
}

impl PostfixExpr {
    pub fn operand(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for PostfixExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == POSTFIX_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ParenExpr {
    pub(crate) syntax: SyntaxNode,
}

impl ParenExpr {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for ParenExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == PAREN_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct CallExpr {
    pub(crate) syntax: SyntaxNode,
}

impl CallExpr {
    pub fn type_args(&self) -> Option<TypeArgs> {
        support::child(&self.syntax)
    }
    pub fn callee(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn args(&self) -> Option<ArgList> {
        support::child(&self.syntax)
    }
}

impl AstNode for CallExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == CALL_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct FieldAccess {
    pub(crate) syntax: SyntaxNode,
}

impl FieldAccess {
    pub fn receiver(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn type_args(&self) -> Option<TypeArgs> {
        support::child(&self.syntax)
    }
}

impl AstNode for FieldAccess {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == FIELD_ACCESS
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct IndexExpr {
    pub(crate) syntax: SyntaxNode,
}

impl IndexExpr {
    pub fn parts(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}

impl AstNode for IndexExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == INDEX_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct NewExpr {
    pub(crate) syntax: SyntaxNode,
}

impl NewExpr {
    pub fn qualifier(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn args(&self) -> Option<ArgList> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<ClassBody> {
        support::child(&self.syntax)
    }
}

impl AstNode for NewExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == NEW_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct AssignmentExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AssignmentExpr {
    pub fn parts(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}

impl AstNode for AssignmentExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ASSIGNMENT_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct TernaryExpr {
    pub(crate) syntax: SyntaxNode,
}

impl TernaryExpr {
    pub fn parts(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}

impl AstNode for TernaryExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == TERNARY_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct LambdaExpr {
    pub(crate) syntax: SyntaxNode,
}

impl LambdaExpr {
    pub fn params(&self) -> Option<LambdaParams> {
        support::child(&self.syntax)
    }
    pub fn block_body(&self) -> Option<Block> {
        support::child(&self.syntax)
    }
    pub fn expr_body(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for LambdaExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == LAMBDA_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct MethodRefExpr {
    pub(crate) syntax: SyntaxNode,
}

impl MethodRefExpr {
    pub fn qualifier(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
}

impl AstNode for MethodRefExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == METHOD_REF_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct CastExpr {
    pub(crate) syntax: SyntaxNode,
}

impl CastExpr {
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
}

impl AstNode for CastExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == CAST_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct SwitchExpr {
    pub(crate) syntax: SyntaxNode,
}

impl SwitchExpr {
    pub fn selector(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn body(&self) -> Option<SwitchBlock> {
        support::child(&self.syntax)
    }
}

impl AstNode for SwitchExpr {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == SWITCH_EXPR
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ClassLiteral {
    pub(crate) syntax: SyntaxNode,
}

impl ClassLiteral {
    pub fn expr(&self) -> Option<Expr> {
        support::child(&self.syntax)
    }
    pub fn ty(&self) -> Option<Type> {
        support::child(&self.syntax)
    }
}

impl AstNode for ClassLiteral {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == CLASS_LITERAL
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct ArrayInit {
    pub(crate) syntax: SyntaxNode,
}

impl ArrayInit {
    pub fn elements(&self) -> AstChildren<Expr> {
        support::children(&self.syntax)
    }
}

impl AstNode for ArrayInit {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == ARRAY_INIT
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct LambdaParams {
    pub(crate) syntax: SyntaxNode,
}

impl LambdaParams {
    pub fn params(&self) -> AstChildren<Param> {
        support::children(&self.syntax)
    }
}

impl AstNode for LambdaParams {
    type Language = JavaLanguage;
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == LAMBDA_PARAMS
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
